const BOARD_SIZE_IN_CELLS = 8;
const CELL_SIZE_PX = 100;
const CELL_SIZE_DESKTOP_XL_PX = 45;
const CELL_SIZE_DESKTOP_PX = 56;
const CELL_SIZE_LAPTOP_PX = 100;
const CELL_SIZE_TABLET_PX = 56;
const CELL_SIZE_MOBILE_PX = 36;
const NUMBER_OF_PIECES = 12;

export {
    BOARD_SIZE_IN_CELLS,
    CELL_SIZE_PX,
    CELL_SIZE_DESKTOP_XL_PX,
    CELL_SIZE_DESKTOP_PX,
    CELL_SIZE_TABLET_PX,
    CELL_SIZE_MOBILE_PX,
    CELL_SIZE_LAPTOP_PX,
    NUMBER_OF_PIECES,
}