const BOARD_SIZE_IN_CELLS = 8;
const NUMBER_OF_PIECES = 12;
const SIDE_CONTENT_SIZE_IN_PIXELS = 500;
const TOP_CONTENT_SIZE_IN_PIXELS = 200;
const MOBILE_TOP_CONTENT_SIZE_IN_PIXELS = 80;

export {
    BOARD_SIZE_IN_CELLS,
    NUMBER_OF_PIECES,
    SIDE_CONTENT_SIZE_IN_PIXELS,
    TOP_CONTENT_SIZE_IN_PIXELS,
    MOBILE_TOP_CONTENT_SIZE_IN_PIXELS,
}